### ISSUE TITLE
borders in 1.3.1 are now missing on all windows.

### ISSUE THREAD

**Issue by jazztickets** [shimmerproject/Greybird#50] opened 2014-02-20 05:35 UTC
http://i.imgur.com/ny3kjHG.png

They're not black they're just transparent.

**Comment by CrazyCasta** [comment] 2015-01-07 01:10
Just FYI: https://bugs.freedesktop.org/show_bug.cgi?id=54168 has been resolved and should be in 1.16.2.901 and 1.16.3. Those were just released a tad less then a month though, so you may not have a package yet.

**Comment by ochosi** [comment] 2015-01-12 08:58
Thanks, as this is obviously not a bug in Greybird but in xorg, I'm closing this issue.

**Closed by ochosi** 2015-01-12 08:58 UTC
