### ISSUE TITLE
Gtk 3.20 broke Greybird

### ISSUE THREAD

**Issue by fredmorcos** [shimmerproject/Greybird#123] opened 2016-04-11 10:41 UTC
Attached are a bunch of Gtk warning messages from emacs and a screenshot of how the menu-bar looks.

Currently all Gtk 3 applications have broken theming with Greybird and require GTK_THEME=adwaita in Xfce.

[Emacs Gtk Warnings](https://github.com/shimmerproject/Greybird/files/212757/emacs.txt)

![screenshot_2016-04-11_12-35-54](https://cloud.githubusercontent.com/assets/573521/14424666/a46a12ec-ffe2-11e5-98a6-0bbd811e6471.png)

**Comment by jturner314** [comment] 2016-04-11 17:10
I'm experiencing this too. For example, below is a screenshot of Parole 0.8.1 with GTK 3.20.2 and Greybird 1.6.2. You can see that the scrubbing/progress bar is not shown, the button outlines in the open file dialog are not rendered, and the padding between the controls is missing. The warning messages are the same as those reported by @fredmorcos above.

![parole](https://cloud.githubusercontent.com/assets/1836850/14435549/6a732048-ffe6-11e5-8daa-450964886962.png)

**Comment by nonamedotc** [comment] 2016-04-11 21:35
#120

**Comment by ochosi** [comment] 2016-04-11 21:51
This issue is a duplicate of #120

**Closed by ochosi** 2016-04-11 21:51 UTC
