### ISSUE TITLE
Left button edge cut off / GTK+ 3.16

### ISSUE THREAD

**Issue by questmark** [shimmerproject/Greybird#85] opened 2015-04-12 21:19 UTC
This is just a minor cosmetic issue.
I don't know if it's intended to be this way, but the left side of some buttons gets cut off.

GTK3 widget demo:
http://imgur.com/eSy2xvU
Actual GTK3 application (Gedit):
http://imgur.com/PHzUvum

**Comment by ochosi** [comment] 2015-04-16 11:22
I fear issues like these will have to wait until I have Gtk3.16 available myself.

**Comment by ochosi** [comment] 2015-07-15 11:36
The issue with Gedit can also be seen in Evince, but it looks less bad there. The problem is that the GtkEntry is the first child so the go-up button isn't the left child but the middle child (hence the straight border). This can only be fixed by making the GtkEntry as high as the other linked buttons, dunno yet why that isn't the case anyway, but I presume I should add some special styling for that searchbar.

**Comment by ochosi** [comment] 2015-07-15 12:39
Also, I'm starting to suspect I need to update the code for linked buttons to include comboboxes and set homogenous padding for GtkEntrys too.

**Comment by ochosi** [comment] 2015-08-26 14:31
I can meanwhile confirm the issue and will be trying to work out a fix.

**Comment by ochosi** [comment] 2016-07-19 21:22
I have recently rebased Greybird on Adwaita for Gtk3.20 so this issue should be fixed. Please note that I will not backport the fix to Gtk3.16

**Closed by ochosi** 2016-07-19 21:22 UTC
