### ISSUE TITLE
firefox 37 tooltips unreadable

### ISSUE THREAD

**Issue by nirik** [shimmerproject/Greybird#81] opened 2015-04-03 20:37 UTC
Downstream bug: 
https://bugzilla.redhat.com/show_bug.cgi?id=1208888

Since version 37 firefox supports transparent tooltips which causes current tooltips beeing unreadable because of having a transparent background.

**Comment by ochosi** [comment] 2015-04-04 11:08
Strange, I can't reproduce that. I have FF37 too here (Xubuntu 15.04).

**Comment by nirik** [comment] 2015-04-04 12:26
Hum, Could be some difference in the way firefox is compiled? Is the Xubuntu one using gtk3?

**Comment by ochosi** [comment] 2015-04-04 12:29
Nope, Firefox is still using Gtk2 here.

**Comment by nirik** [comment] 2015-04-04 12:30
Yeah, the Fedora one switched to gtk3 not long back.

**Comment by ochosi** [comment] 2015-04-04 12:31
K, so I suppose the tooltips work with other themes? If so, which ones?

**Comment by nirik** [comment] 2015-04-04 12:39
Albatross works fine, bluebird works, but is a grey box with white text and kind of hard to read, Zukitwo works now, but just got a patch: http://pkgs.fedoraproject.org/cgit/zukitwo.git/commit/?id=4459ef0a2d82a1321ea02e315442c3820185a1c8
Happy to try other themes...

**Comment by ochosi** [comment] 2015-04-04 12:45
Could you try again with Greybird from git master? I just pushed a fix for that (ported the one from Zukitwo).

**Comment by nirik** [comment] 2015-04-04 12:53
Thats better, but still really hard to read here. It's a transparent box with very light white letters.

**Comment by ochosi** [comment] 2015-04-07 07:57
I installed firefox-gtk3 now (aka Nightly 38.0a1) and can't reproduce your problem.
![screenshot_2015-04-07_09-56-32](https://cloud.githubusercontent.com/assets/261436/7019083/8076ac46-dd0c-11e4-972d-2988401536b8.png)

**Comment by nirik** [comment] 2015-04-07 12:18
Odd. I'm not sure what the difference could be then... I definitely see it here... 

http://www.scrye.com/~kevin/fedora/firefox-greybird-tab-tooltip.png

**Comment by ochosi** [comment] 2015-04-07 12:30
Well first of all you're not using Greybird in that screenshot and I haven't pushed any fixes for Albatross (which is what your screenshot shows)...

**Comment by hannes101** [comment] 2015-04-07 12:34
Could be also caused by your firefox theme or is this the default?

**Comment by nirik** [comment] 2015-04-07 14:47
greybird was definitely set. Here's another screenshot showing the appearance applet with greybird selected:

http://www.scrye.com/~kevin/fedora/firefox-greybird-tab-tooltip2.png

I was using the darkfox theme, but switching back to default doesn't really change anything with the tooltips.

**Comment by ochosi** [comment] 2015-04-08 13:15
Firefox doesn't really use Gtk but Xul, so quite often you need to restart it in order to fully apply a theme. So what's shown in your screenshot for Firefox still isn't Greybird (look at the scrollbars...)

I checked ZukiTwo and if it works with that, I don't see any reason why it wouldn't with Greybird. The code for the tooltips is practically identical now.

**Comment by nirik** [comment] 2015-04-08 22:30
ah, good point indeed. ;) I will do some more testing with restarts...

**Comment by nirik** [comment] 2015-04-08 22:38
ok indeed, that fixes it. :) Sorry for the testing fail here...

**Closed** 2015-04-09 08:50 UTC
