### ISSUE TITLE
Glitches of the gtk3.20 branch

### ISSUE THREAD

**Issue by tambeta** [shimmerproject/Greybird#133] opened 2016-07-19 14:16 UTC
I am using the new gtk3.20 branch on updated Arch Linux, XFCE 4.12, GTK 3.20.6, Firefox 47.0.1, network-manager-applet 1.2.2. Reporting some graphical glitches of I've come across. If it is more convenient, I can report each as a separate issue.

* Firefox: location bar and search bar dropdowns do not have borders. Note that I'm using the Classic Theme Restorer extenison, but the borders are not present when turning it off. [Example](https://cloud.githubusercontent.com/assets/9417744/16952759/3ef03c36-4dd3-11e6-818e-eed757aa063c.png)
* Firefox: the context menu does not have borders. [Example](https://cloud.githubusercontent.com/assets/9417744/16952756/3ee7af94-4dd3-11e6-904f-ce51cadae316.png)
* Network Manager applet in the system tray: left-click context menu has an unsightly disabled entry. [Example](https://cloud.githubusercontent.com/assets/9417744/16952758/3eeb38a8-4dd3-11e6-8263-dc92492fe4d8.png)
* Various applications, e.g. Firefox print dialog, Gnome Terminal: tabs seem to have too large spacing. [Example](https://cloud.githubusercontent.com/assets/9417744/16952757/3eeaf136-4dd3-11e6-94a1-bfaa73a5f132.png)

Also, thank you for the work on an excellent GTK theme!

**Comment by ochosi** [comment] 2016-07-19 21:44
Hey, the Firefox issues could be due to Firefox not really supporting Gtk3.20, but I wouldn't know for sure.

Disabled items in the nm-applet left-click menu in the systray look ok here. I don't have an ethernet interface in my laptop so I'm not sure how to reproduce this problem. How does it look with Adwaita?

Yeah, the tabs are still a little bit work in progress, this part should be easy to fix though.

**Comment by tambeta** [comment] 2016-07-20 12:30
You're right, I believe Firefox indeed does not support 3.20 yet. Luckily it can be compiled against GTK2. `nm-applet` looks the same with Adwaita. The menu entry in question is supposed to be a separator with a title, i.e. the gray boxes on either side are meant to be 1px high horizontal lines. This is likely some hack that was broken by GTK 3.20.

So this leaves the tabs, and as you said that's already work in progress.

**Comment by ochosi** [comment] 2016-07-20 22:07
Tabs should be fixed now and as you mentioned the rest is not really Greybird's fault. Consequently closing this issue.

Thanks for testing though and feel free to report more issues as you find them!

**Closed by ochosi** 2016-07-20 22:07 UTC
