### ISSUE TITLE
Broken window shadows in gtk 3.18

### ISSUE THREAD

**Issue by IdiotEbrilo** [shimmerproject/Greybird#119] opened 2016-02-02 09:45 UTC
I can reproduce this bug on two clean installs of Arch with gnome-shell (pls see screenshot).

http://storage9.static.itmages.com/i/16/0202/h_1454405743_5739694_9e11a06fd3.png

There is something awry - some native gnome3 apps (like gnome-terminal) have broken shadows, some other not less native (like nautilus) have normal ones, and these broken shadows are not affected by any change in css.

**Comment by IdiotEbrilo** [comment] 2016-02-02 12:22
Well, I can't say this is a proper fix, but changing _box-shadow_ of _.window-frame_ and _.window-frame:backdrop_ classes in _gtk-widgets.css_ to _0 3px 6px alpha(black, 0.47), 0 0 0 1px alpha(black, 0.3);_ seems to be something like workable.

Anyway, have no idea, why windows without titlebar action buttons have broken shadows...

**Comment by ochosi** [comment] 2016-03-07 22:30
This is odd, I can't reproduce this in Ubuntu Xenial (with Gtk3.18). It's possible though that Gtk3 behaves a little differently there as it's usually patched by Ubuntu (in this case possibly to play along nicely with Compiz?).

Anyhow, speculation shmeculation...

**Comment by ochosi** [comment] 2016-03-07 22:31
(Only to extend my previous comment: applications with headerbars - even *native* ones, as you call them - like Gedit work fine. Specifically gnome-terminal has the headerbars patched out in Ubuntu though, so I can't check that one.)

**Comment by arshavindn** [comment] 2016-03-23 03:37
I'm using Ubuntu Gnome with Gnome 3.18 and this issue happens to me

**Comment by ochosi** [comment] 2016-03-24 20:31
@arshavindn With which apps? I couldn't reproduce this problem with gnome-terminal.

**Comment by arshavindn** [comment] 2016-03-25 08:22
@ochosi vlc, nemo...

**Comment by ochosi** [comment] 2016-03-29 20:52
@arshavindn vlc and firefox are not Gtk+ apps so maybe this is actually a problem with the metacity/mutter theme. Can you reproduce the problem with Greybird as Gtk+ theme but using a different window manager theme?

**Comment by arshavindn** [comment] 2016-03-30 05:22
Since gnome 3.16, gnome theme does not use metacity anymore... so I'm using ubuntu gnome and it's just having gtk theme to change in gnome-tweak-tools

**Comment by ochosi** [comment] 2016-04-07 21:26
Gnome still uses a window decorator for applications that don't support Client-Side Decorations (drawn by Gtk itself) yet, in Gnome3 that's mutter (used to be metacity).

Not sure about how to change Gtk+ theme and window manager theme independently in Gnome, I'm fairly sure it's possible (I vaguely remember doing that myself once in dconf-editor when testing something in Gnome) but I guess you have to ask Google.

**Comment by ochosi** [comment] 2016-07-19 21:24
Closing this issue as I won't work on fixing issues in Gtk3.18 anymore. If the issue pops up in Gtk3.20 again (after I've released the gtk3.20 branch) feel free to re-open this issue or submit a new one. Thanks!

**Closed by ochosi** 2016-07-19 21:24 UTC
