### ISSUE TITLE
Right click margin

### ISSUE THREAD

**Issue by Paviluf** [shimmerproject/Greybird#213] opened 2017-12-31 11:24 UTC
Hello,

Is it possible to increase the right click margin from the cursor ? Now when you right click sometimes the first action is triggered because the first item is directly selected.
![capture du 2017-12-28 13-43-32](https://user-images.githubusercontent.com/17159065/34461212-3866c6a2-ee25-11e7-9af6-6c520fa9945b.png)

With adwaita the problem is not present
![capture du 2017-12-28 13-42-48](https://user-images.githubusercontent.com/17159065/34461213-3d6e4f8a-ee25-11e7-9373-a4eca6e49eb8.png)

The problem is not present too with other desktop environement
![capture du 2017-12-28 13-39-51](https://user-images.githubusercontent.com/17159065/34461216-439c9aa6-ee25-11e7-9321-2c6a2abfc94d.png)

Thanks !

**Comment by DarkTrick** [comment] 2021-09-26 01:36
I think this is fixed(?) Please close the issue, if it's fixed.

**Comment by ochosi** [comment] 2021-09-28 12:20
I also cannot reproduce. Please reopen if this isn't fixed yet.

**Closed by ochosi** 2021-09-28 12:20 UTC
