### ISSUE TITLE
Alt-Tab menu unusable if configured to be a list

### ISSUE THREAD

**Issue by akosladanyi** [shimmerproject/Greybird#283] opened 2020-08-20 17:40 UTC
If "Cycle through windows in a list" is enabled in the window manager tweaks the switcher menu becomes unusable due to the similar colors used for the background and the selected entry.

**Comment by andreldm** [comment] 2020-09-04 03:13
@akosladanyi duplicate of #272? If not, please post screenshots.

**Comment by akosladanyi** [comment] 2020-09-04 21:49
Yes, this is a duplicate.

**Closed** 2020-09-04 21:50 UTC
