### ISSUE TITLE
Broken with firefox 45

### ISSUE THREAD

**Issue by alexforencich** [shimmerproject/Greybird#126] opened 2016-04-22 03:22 UTC
Invisible scrollbars, missing button boarders, invisible highlights, etc.  Bluebird is also affected.  DarkOrangeBird and Blackbird are not affected.

**Comment by alexforencich** [comment] 2016-04-22 04:40
Actually, amend that, they all seem to be affected to different extents.  None of them display scroll bars or button borders.  Blackbird and DarkOrangeBird show highlights and seem to display buttons incorrectly instead of not at all.

**Comment by ochosi** [comment] 2016-04-24 21:13
Sorry, I've never seen anything like this before. Could you post some more informations about the environment you're seeing this in (distribution, Gtk+3 version etc) so I have a better chance of reproducing?

Also, note that Firefox is not using Gtk+ directly, so it's unlikely that this is really a bug in Greybird (but we shall see).

**Comment by alexforencich** [comment] 2016-04-24 22:33
Well, it definitely has something to do with greybird as changing the theme to something other than greybird immediately restores the scroll bars, highlights, buttons, etc.  

I am running Arch Linux.  I am running some updates right now; I will post package versions and what not in a few minutes.

**Comment by alexforencich** [comment] 2016-04-25 00:12
Versions:

$ yaourt -Q gtk2 gtk3 firefox xfce-theme-greybird-git xfce-theme-blackbird linux-lts xfwm4
extra/gtk2 2.24.30-1
extra/gtk3 3.20.3-1
extra/firefox 45.0.2-1
local/xfce-theme-greybird-git 1.6.2.r648-1
local/xfce-theme-blackbird 0.4-2
core/linux-lts 4.4.8-1
extra/xfwm4 4.12.3-1 (xfce4)

Let me know if there are any other packages that I need to look at.  

Screenshots:

![greybird-bug1](https://cloud.githubusercontent.com/assets/508807/14771431/96dd7102-0a3f-11e6-8c22-e354081e2624.png)
![greybird-bug2](https://cloud.githubusercontent.com/assets/508807/14771432/991e37da-0a3f-11e6-8183-43285fb33f21.png)
![greybird-bug3](https://cloud.githubusercontent.com/assets/508807/14771433/9a579a6a-0a3f-11e6-852d-401b0d5d2a52.png)

**Comment by alexforencich** [comment] 2016-04-25 01:37
And it seems that this also affects gedit and possibly many other applications.  gedit is no longer coloring selected text.

**Comment by alexforencich** [comment] 2016-04-25 02:00
After some more experimenting:

Also affected: firefox non-styled form elements and scrollbars and print and save dialogs, gedit and its associated print, open, save, and preferences dialogs, libreoffice menus and dialogs, evince menus and dialogs
Not affected: thunderbird, xfce terminal, thunar, sublime text, gnucash, kicad, gtkwave, smplayer, vlc, gimp, inkscape, audacity, pidgin, wicd

**Comment by szczur90** [comment] 2016-04-25 11:36
I'm also affected by the problem. I think it's again problem with gtk 3.20. Every program that used it like Pavucontrol, Transmission, Fileroller etc. is affected and since firefox is onging a transision to GTK maybe they changed something recently that tries to use GTK but just my guess.

**Comment by alexforencich** [comment] 2016-04-25 16:39
Yeah, I agree that it seems like there is some issue with gtk 3 that has been brewing for some time (I have noticed some issues with gedit previously) and that Firefox is just a red herring as they may have switched a few things around internally in the latest version.

**Comment by ochosi** [comment] 2016-04-26 19:41
Alright, this is a duplicate of #120

**Closed by ochosi** 2016-04-26 19:41 UTC
