### ISSUE TITLE
Themes broken in GTK>=3.19

### ISSUE THREAD

**Issue by nonamedotc** [shimmerproject/Greybird#120] opened 2016-03-13 20:03 UTC
Due to recent updates in GTK-3.19+[1], greybird themes do not have the clean appearance they usually have. I believe this requires an update to greybird incorporating changes in GTK-3.19+

[1] https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/

**Comment by ochosi** [comment] 2016-03-15 00:07
Yes, Greybird doesn't support Gtk+ 3.19 yet and since it will be a rewrite of the theme I guess I won't get to it very soon.
That said, if anyone wants to start working on that, that'd be appreciated!

**Comment by jristz** [comment] 2016-04-12 01:27
I should add bug for bluebird and albatross and orion too, or (indifferent if greybord is the priority) this bug is enough to keep users aware of the problem in the themes?

**Comment by tuxy** [comment] 2016-04-12 17:15
I'm using XFCE 4.12 + Greybird v1.6.2 and I can confirm that its broken with latest upgrade of GTK3. Most notably its broken when using Firefox v45.

@ochosi "Yes, Greybird doesn't support Gtk+ 3.19 yet and since it will be a rewrite of the theme I guess I won't get to it very soon." That too bad, as I've been using this greybird theme for many years. Now I'm forced to find alternatives at least until its fixed. =((

**Comment by jristz** [comment] 2016-04-14 23:49
I was reading some forums and may guys point that in the mailist of gnome they mentioned that gtk 3.22 will change some theming part will change again and likely break theming but in a less ugly way.
But I can't find in the mailist the reference, but anyway, beware, maybe better look for gtk3.21 instead.

**Comment by tuxy** [comment] 2016-04-15 05:00
I'm using "arc-dark" (https://github.com/horst3180/Arc-theme) as an alternative for now. Also using Faenza Icons (http://tiheum.deviantart.com/art/Faenza-Icons-173323228) and Firefox theme "arc-darker" (https://github.com/horst3180/arc-firefox-theme) Firefox theme is also available on (https://addons.mozilla.org/en-US/firefox/themes/)

**Comment by ochosi** [comment] 2016-04-16 20:38
@jristz Actually pretty much every Gtk+3 release so far broke the theming...

Note that 3.20 is still fairly new and as I'm on Ubuntu, it'll take a few more months for me to get it and to work on the necessary updates.

Furthermore, I'm planning to rewrite the theme from scratch based on Adwaita and in SASS for better maintainability (the css is slowly but surely getting unreadable). _If any of you want to help_, please contribute and send pull requests!

**Comment by corsac-s** [comment] 2016-04-17 09:34
I've submitted PR #125 but it's far from complete and maybe not the right way at all (duplicating code all around).

**Comment by louwers** [comment] 2016-05-20 00:55
I sincerely believe that this is the most ergonomic, pragmatic and beautiful GTK theme around. I doubt I will be able to be of much help because I have zero experience with GTK themes, but I will see what I can do.

Thank you for your effort on this. :+1:

**Comment by ochosi** [comment] 2016-05-22 19:57
@louwers Thanks for the praise!

**Comment by kuboosoft** [comment] 2016-05-31 07:29
Hi, I love greybird theme, but in Fedora 24 XFCE (Gtk 3.20.6) doesn't display, edges in buttons, contextual menus and others

**Comment by cinquecento** [comment] 2016-06-06 23:07
Upstream: Greybird GTK-3.20 port - based on Blackbird theme
https://bugzilla.redhat.com/attachment.cgi?id=1165425

GTK+ 3.20 port - based on Blackbird theme, work of Eric Koegel
incl. LightDM Greeter GTK+ 3.20 port and gtk-widgets.css GTK+ 3.20 tune up,
base states, entry, switch and textview

Test builds - Fedora:
http://goo.gl/Gm4ffO
themes

**Comment by cinquecento** [comment] 2016-06-06 23:39
A couple of references ...

MATE Desktop themes
https://github.com/mate-desktop/mate-themes

The Adwaita theme
https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita

GtkParasite Css Editor
https://github.com/chipx86/gtkparasite

Live Editing GTK CSS With GTK-Parasite | Just Sweet!
http://worldofgnome.org/live-editing-gtk-css-with-gtk-parasite-just-sweet

Rename parasite to gtkinspector
https://git.gnome.org/browse/gtk+/commit/?id=ccff3e9

GtkInspector Css Editor
https://git.gnome.org/browse/gtk+/tree/gtk/inspector

GtkInspector
https://wiki.gnome.org/Projects/GTK%2B/Inspector

Introducing GtkInspector
https://blogs.gnome.org/mclasen/2014/05/15/introducing-gtkinspector

Tweaking a the GTK+ theme, using CSS
https://blogs.gnome.org/mclasen/2014/05/06/tweaking-a-the-gtk-theme-using-css

to paraphrase,
... ask not what your theme can do for you, ask what you can do for your theme.

**Comment by ilikenwf** [comment] 2016-06-18 23:22
I can confirm that the 3.20 patch works well on my system.

Archlinux, gtk3 3.20.6

**Comment by jEsuSdA** [comment] 2016-06-21 10:32
I've just install the 20160619 package version and it works fine, but there are several bugs on certain buttons and fields (see the synaptic screenshot and look at the buttons, search field and menu).

Thanks for your work!! Greybird is awesome!!

![screenshot54](https://cloud.githubusercontent.com/assets/5833446/16226543/32a9d42e-37ac-11e6-8450-07c948df9055.png)

**Comment by jEsuSdA** [comment] 2016-06-21 10:36
Another app with issues I've just detected: Synfig

![screenshot55](https://cloud.githubusercontent.com/assets/5833446/16226643/b60a29ae-37ac-11e6-87af-c8fb9ea53b1f.png)

**Comment by ochosi** [comment] 2016-06-28 08:59
Sorry to respond so late, I was fairly busy lately.

Thanks for your contribution! I looked at the patch and I guess this could work, but it's not a very maintainable solution. If you look at the shear length of the contained.css file and the amount of selectors and nodes in some lines, that's so far from readable...

I guess the only way to move forward is - and in that respect the approach was correct - to rebase on top of Adwaita, however also using Adwaita's system (SCSS/SASS). Otherwise we'll always fight with unreadable walls of text.

I also realize that if I don't get to porting Greybird to the system laid out above everyone else will still need some sort of working version in the meantime, so I might end up pushing the patch by poma until I have something better.

**Comment by ochosi** [comment] 2016-06-29 07:32
As I'm about to start testing the patch myself I also pushed it to a branch so it's easier for others to try it out:
https://github.com/shimmerproject/Greybird/tree/gtk3.20

**Comment by ochosi** [comment] 2016-07-04 11:10
Just to let you all know, I've set up Gtk3.20 for myself and I've started the porting fun. Please forget about the branch I mentioned above, I'll delete it shortly.

**Comment by abhis3k** [comment] 2016-07-11 05:09
@cinquecento This patch works perfectly :+1: 
I am back with Greybird on Debian Stretch

**Comment by ochosi** [comment] 2016-07-18 07:09
OK, finally some news on this. Here's my WIP version of Greybird for Gtk3.20. There are several tweak-worthy things but I hope that it will mostly work for everyone without eye-bleeding.
https://github.com/shimmerproject/Greybird/tree/gtk3.20

For all those waiting, sorry it took so long.

Hope I can do a first release of this soon.

Please note that I will likely not do any more maintenance releases or backports for Gtk<=3.18. The changes were just too dramatic.

**Comment by jEsuSdA** [comment] 2016-07-20 16:54
It works fine! :+1: 
I'll notify you if I found any bug. ;)
Thank you so much!!!

**Comment by codeforkjeff** [comment] 2016-07-21 22:23
This is looking fantastic, many thanks for your work on this!

FYI, the vertical scrollbar doesn't display correctly for me in Firefox 47.0.1 on Debian testing (stretch). It just looks like a single solid gray bar. In other applications (xfce terminal and gimp, just to pick two at random), the scrollbar displays fine.

**Comment by jbicha** [comment] 2016-07-21 22:50
@codeforkjeff Where did you install your Firefox from? firefox-esr included in Debian testing works fine here with greybird built from the gtk-3.20 branch.

**Comment by codeforkjeff** [comment] 2016-07-21 22:57
@jbicha I'm using a tarball I downloaded from the Mozilla website. Starting with Firefox 46, the official tarballs are compiled against gtk3. The firefox-esr package in Debian testing is at 45.2.0.

**Comment by jbicha** [comment] 2016-07-21 22:59
Firefox 47 does not support GTK 3.20 and has bugs like the scrollbar issue you mentioned. You need at least Firefox 48 (currently in Beta) although some bugs aren't fixed until 49.

**Comment by jbicha** [comment] 2016-07-21 23:00
Alternatively, if you're compiling it yourself, you could stay with 47 and grab the GTK 3.20 patch from, say, [Fedora](http://pkgs.fedoraproject.org/cgit/rpms/firefox.git/tree/firefox-gtk3-20.patch).

**Comment by codeforkjeff** [comment] 2016-07-21 23:09
@jbicha Thanks for the info! I just tried the 48b07 tarball from the Beta downloads section, and it does indeed fix the scrollbar issue. So definitely not a Greybird problem.

**Comment by ochosi** [comment] 2016-08-16 09:00
Merged to master, hence this is fixed: https://github.com/shimmerproject/Greybird/commit/688b10c49752e89972d051d8cd67b8004b9db952

**Closed by ochosi** 2016-08-16 09:00 UTC
