### ISSUE TITLE
Little things in Firefox 52+

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#197] opened 2017-06-29 11:34 UTC
I've noticed two little things when updating Firefox to 52 version:

The first one is the popup menu separators. They have stronger border than other separators.

Here a normal drop-down or popup menu:

![screenshot30](https://user-images.githubusercontent.com/5833446/27685607-48db98b0-5ccf-11e7-94a4-f12159a91137.png)

And here the Firefox one:

![screenshot29](https://user-images.githubusercontent.com/5833446/27685611-4ead664c-5ccf-11e7-876c-d9fa3294ddcc.png)

Look at the horizontal separators.

The other thing I've realized is that the "save window" buttons have smaller size than the normal ones:

![screenshot31](https://user-images.githubusercontent.com/5833446/27685697-a8e78c50-5ccf-11e7-8938-0efd265b03e6.png)

As you can see, "Cancelar" (cancel) and "Aceptar" (accept) buttons are thinner.

Thanks a lot for your efforts. ;)

**Comment by ochosi** [comment] 2017-06-30 22:21
Firefox doesn't use Gtk+, it only mimicks it (with the help of XUL) so I cannot fix theming there if it's broken.

The small buttons most likely come from the fact that you probably have disabled button images and then the padding just collapses away (again, not Greybird's fault).

**Comment by jEsuSdA** [comment] 2017-07-04 11:02
I don't understand.

If Firefox does not use GTK+, why GTK+ is needed to compile and run it?
https://packages.debian.org/sid/firefox

The previous version of Firefox needed GTK+2 and they looks great. The new 52 version uses GTK+3 and I think this causes these glitches.

As you can see here, when using Zukitre theme, the glitches does not appears:
![screenshot35](https://user-images.githubusercontent.com/5833446/27827686-cb498a7c-60b8-11e7-8996-9935eec90c26.png)

So, I think, if the Firefox appearance changes when the GTK theme changes, How can the Firefox appearance being no related with GTK?

Thanks. ;)

**Comment by jEsuSdA** [comment] 2017-07-13 07:21
Definitively, there are something related with GTK+3 and Firefox and Thunderbird: #198

**Comment by ochosi** [comment] 2017-07-13 12:07
What distribution are you using? I can't reproduce any of the issues you mention or show in your screenshots.

Menu:
http://i.imgur.com/jKktswK.png

The download dialog here (Xubuntu 17.04) is just the standard Gtk+ dialog.

**Comment by jEsuSdA** [comment] 2017-07-14 10:36
I'm using Debian Testing:

![screenshot4](https://user-images.githubusercontent.com/5833446/28208969-b5a890de-6890-11e7-8968-4d7e5fb26456.png)


-- Package-specific info:

Name: Default theme
Location: /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
Package: firefox
Status: enabled
Name: Español (España) Language Pack locale
Location: /usr/lib/firefox/browser/extensions/langpack-es-ES@firefox.mozilla.org.xpi
Package: firefox-l10n-es-es
Status: enabled

Name: Firebug
Location: ${PROFILE_EXTENSIONS}/firebug@software.joehewitt.com.xpi
Status: enabled

Name: Firefox Hello Beta
Location: ${PROFILE_EXTENSIONS}/loop@mozilla.org.xpi
Status: enabled

Name: FirefoxNotify
Location: /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/firefoxnotify@abhishek.mukherjee
Package: xul-ext-notify
Status: app-disabled

Name: Flashblock
Location: ${PROFILE_EXTENSIONS}/{3d7eb24f-2740-49df-8937-200b1cc08f8a}
Status: user-disabled

Name: FlashGot
Location: ${PROFILE_EXTENSIONS}/{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}.xpi
Status: enabled

Name: Password Exporter
Location: ${PROFILE_EXTENSIONS}/{B17C1C5A-04B1-11DB-9804-B622A1EF5492}.xpi
Status: user-disabled

Name: ReloadEvery
Location: ${PROFILE_EXTENSIONS}/{888d99e7-e8b5-46a3-851e-1ec45da1e644}.xpi
Status: user-disabled

Name: ScrapBook
Location: ${PROFILE_EXTENSIONS}/{53A03D43-5363-4669-8190-99061B2DEBA5}.xpi
Status: enabled

Name: Screenshoter Fixed
Location: ${PROFILE_EXTENSIONS}/{d9babd10-47de-11df-9879-0800200c9a67}.xpi
Status: enabled

Name: Session Manager
Location: ${PROFILE_EXTENSIONS}/{1280606b-2510-4fe0-97ef-9b5a22eafe30}.xpi
Status: enabled

Name: Spanish (Spain) Dictionary dictionary
Location: ${PROFILE_EXTENSIONS}/es-es@dictionaries.addons.mozilla.org
Status: enabled

Name: Tab Mix Plus
Location: ${PROFILE_EXTENSIONS}/{dc572301-7619-498c-a57d-39143191b318}.xpi
Status: enabled

Name: uBlock Origin
Location: ${PROFILE_EXTENSIONS}/uBlock0@raymondhill.net.xpi
Status: enabled

Name: Video DownloadHelper
Location: ${PROFILE_EXTENSIONS}/{b9db16a4-6edc-47ec-a1f4-b86292ed211d}.xpi
Status: enabled

Name: Web Developer
Location: ${PROFILE_EXTENSIONS}/{c45c406e-ab73-11d8-be73-000a95be3b12}.xpi
Status: enabled


-- Plugins information
Name: DivX Browser Plug-In
Location: /usr/lib/mozilla/plugins/mplayerplug-in-dvx.so
Package: mozilla-mplayer
Status: enabled

Name: DjView-4.10.6
Location: /usr/lib/mozilla/plugins/nsdejavu.so
Package: djview-plugin
Status: enabled

Name: GNOME Shell Integration
Location: /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
Package: gnome-shell
Status: enabled

Name: Google Talk Plugin
Location: /opt/google/talkplugin/libnpgoogletalk.so
Status: enabled

Name: Google Talk Plugin Video Renderer
Location: /opt/google/talkplugin/libnpo1d.so
Status: enabled

Name: Java(TM) Plug-in 10.40.2 (10.40.2)
Location: /usr/lib/jvm/java-7-oracle/jre/lib/amd64/libnpjp2.so
Status: enabled

Name: MozPlugger 1.14.5 handles QuickTime and Windows Media Player Plugin (1.14.5)
Location: /usr/lib/mozilla/plugins/mozplugger.so
Package: mozplugger
Status: enabled

Name: mplayerplug-in 3.55
Location: /usr/lib/mozilla/plugins/mplayerplug-in.so
Package: mozilla-mplayer
Status: enabled

Name: QuickTime Plug-in 7.4.5
Location: /usr/lib/mozilla/plugins/mplayerplug-in-qt.so
Package: mozilla-mplayer
Status: enabled

Name: RealPlayer 9
Location: /usr/lib/mozilla/plugins/mplayerplug-in-rm.so
Package: mozilla-mplayer
Status: enabled

Name: Shockwave Flash (26.0.0.137)
Location: /opt/mint-flashplugin-11/libflashplayer.so
Package: mint-flashplugin-11
Status: enabled

Name: Shockwave Flash (26.0.0.137)
Location: /usr/lib/flashplayer-mozilla/libflashplayer.so
Package: flashplayer-mozilla
Status: enabled

Name: Windows Media Player Plug-in
Location: /usr/lib/mozilla/plugins/mplayerplug-in-wmp.so
Package: mozilla-mplayer
Status: enabled


-- Addons package information
ii  djview-plugin  4.10.6-1     amd64        Browser plugin for the DjVu image
ii  firefox        45.0.2-1     amd64        Mozilla Firefox web browser
ii  firefox-l10n-e 45.0.2-1     all          Spanish (Spain) language package 
ii  flashplayer-mo 3:26.0.0.137 amd64        Adobe Flash Player
ii  gnome-shell    3.22.3-3     amd64        graphical shell for the GNOME des
ii  mint-flashplug 11.2.202.554 amd64        Adobe Flash plugin 11
ii  mozilla-mplaye 3.55-1.1     amd64        MPlayer-Plugin for Mozilla
ii  mozplugger     1.14.5-2+b1  amd64        Plugin allowing external viewers 
ii  xul-ext-downlo 0.9.7.2-1    all          Iceweasel/Firefox addon that prov
ii  xul-ext-linky  3.0.0-4      all          iceweasel extension to handle web
ii  xul-ext-notify 1.5.4-4      all          integrate Iceweasel/Firefox downl

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (500, 'testing'), (500, 'stable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.9.0-3-amd64 (SMP w/4 CPU cores)
Locale: LANG=es_ES.utf8, LC_CTYPE=es_ES.utf8 (charmap=UTF-8), LANGUAGE=es_ES.utf8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/bash
Init: sysvinit (via /sbin/init)

Versions of packages firefox depends on:
ii  debianutils               4.8.1.1
ii  fontconfig                2.12.3-0.1
ii  libasound2                1.1.3-5
ii  libatk1.0-0               2.22.0-1
ii  libc6                     2.24-12
ii  libcairo2                 1.14.10-1
ii  libdbus-1-3               1.10.20-1
ii  libdbus-glib-1-2          0.108-2
ii  libevent-2.0-5            2.0.21-stable-3
ii  libffi6                   3.2.1-6
ii  libfontconfig1            2.12.3-0.1
ii  libfreetype6              2.8-0.2
ii  libgcc1                   1:7.1.0-7
ii  libgdk-pixbuf2.0-0        2.36.5-2
ii  libglib2.0-0              2.52.3-1
ii  libgtk2.0-0               2.24.31-2
ii  libhunspell-1.3-0         1.3.3-4
ii  libnspr4                  2:4.15-1
ii  libnss3                   2:3.31-1
ii  libpango-1.0-0            1.40.6-1
ii  libsqlite3-0              3.19.3-3
ii  libstartup-notification0  0.12-4+b2
ii  libstdc++6                7.1.0-7
ii  libvpx3                   1.5.0-2
ii  libx11-6                  2:1.6.4-3
ii  libxcomposite1            1:0.4.4-2
ii  libxdamage1               1:1.1.4-2+b3
ii  libxext6                  2:1.3.3-1+b2
ii  libxfixes3                1:5.0.3-1
ii  libxrender1               1:0.9.10-1
ii  libxt6                    1:1.1.5-1
ii  procps                    2:3.3.12-3
ii  zlib1g                    1:1.2.8.dfsg-5

Versions of packages firefox recommends:
ii  gstreamer1.0-libav         1:1.12.1-dmo1
ii  gstreamer1.0-plugins-good  1.12.1-1

Versions of packages firefox suggests:
ii  fonts-lmodern          2.004.5-3
ii  fonts-stix [otf-stix]  1.1.1-4
ii  libcanberra0           0.30-3
ii  libgnomeui-0           2.24.5-3.1
ii  libgssapi-krb5-2       1.15-1
ii  mozplugger             1.14.5-2+b1

-- no debconf information

**Comment by andrei-a-papou** [comment] 2017-07-28 10:34
@jEsuSdA I have the same problem. I worked around the separators issue with a custom `userChrome.css`:

`@namespace
url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
/* Make separators fit better with Greybird theme */
menuseparator {
    -moz-appearance: none !important;
    border-bottom: 1px solid #c9c9c9;
    /*
    margin-right: 3px;
    margin-left: 3px;
    */
}
`
With the margin declarations commented out as above, separators take full width of the menu.

The small buttons do not bother me, so I left them as is. Apparently the button issue is no longer reproducible with latest stable Firefox, by the way.

**Comment by jEsuSdA** [comment] 2017-07-29 11:07
@andrei-a-papou , How I may use this userChrome.css? I mean, where I must to copy or edit it?

Thanks!

**Comment by andrei-a-papou** [comment] 2017-08-09 07:00
@jEsuSdA  Take a look here: http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes

**Comment by jEsuSdA** [comment] 2017-08-14 07:03
Thank you @andrei-a-papou . I'll take a look! ;)

By the way, adding 

`separator { color: #e3e3e3;}`

to the main gtk-contained.css fixes the separator colors in pop-up menu, etc.

;)

**Comment by andrei-a-papou** [comment] 2017-08-14 12:36
@jEsuSdA The latest stable version of Firefox (55.0.1 at this time) doesn't seem to have the separator issue. So fiddling with userChrome.css won't be needed in the future. I guess Mozilla fixed it on their end.

**Comment by andrei-a-papou** [comment] 2017-08-14 12:36
@jEsuSdA No problem. The latest stable version of Firefox (55.0.1 at this time) doesn't seem to have the separator issue. So fiddling with userChrome.css won't be needed in the future. I guess Mozilla fixed it on their end.

**Comment by jEsuSdA** [comment] 2017-08-14 14:29
A small userChrome.css modification to bring Greybird gradient to Firefox:

![screenshot1](https://user-images.githubusercontent.com/5833446/29276035-8ccab832-810d-11e7-959d-029d3b759755.png)

also including user toolbar and web developer toolbar:
![screenshot2](https://user-images.githubusercontent.com/5833446/29276047-9704100a-810d-11e7-8e24-22e024762e5a.png)


Copy the userChrome.css to 
/home/<user>/.mozilla/firefox/<profile>/chrome/

[userChrome.css.zip](https://github.com/shimmerproject/Greybird/files/1222495/userChrome.css.zip)

;)

**Comment by jEsuSdA** [comment] 2017-09-08 17:21
Updated userChorme.css for Firefox.

* Increase button size.

[userChrome.css.zip](https://github.com/shimmerproject/Greybird/files/1288633/userChrome.css.zip)

**Comment by stefson** [comment] 2017-09-10 10:34
This looks pretty good. For which version of firefox is the custom css code meant? I am using firefox-52.3esr and it is terrible annoying with the lines in the context menu and the tiny buttons in the download dialog.

**Comment by jEsuSdA** [comment] 2017-09-10 17:33
@stefson , I'm using Firefox 52.3.0.

Try the userChrome.css together with Greybird and it will look great! ;)

**Comment by pedrofleck** [comment] 2019-06-04 22:23
None of the OP issues are present on the latest (tested with 65, 66 and 67) version of Firefox, I believe this bug can be closed.

**Comment by ochosi** [comment] 2019-06-05 05:23
Alright, thanks for checking. Closing...

**Closed** 2019-06-05 05:23 UTC
